services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ${HOME_DIR}/web:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - local
      - proxy
    depends_on: 
      - wordpress
      
  db:
    image: mysql:lts
    volumes:
      - ${HOME_DIR}/db:/var/lib/mysql
    restart: unless-stopped
    command: --innodb-buffer-pool-size=512M --innodb-log-file-size=128M --query-cache-size=0 --query-cache-type=0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASSWORD: ${MYSQL_APP_PASSWORD}
    networks:
      - local
 
 # redis:
 #   image: redis:alpine
 #   restart: always
 #   volumes:
 #     /srv/docker/wp-maker/redis:/data
 # networks:
 #   - local

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ${HOME_DIR}/web:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_APP_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_APP_PASSWORD}
      # WP_REDIS_HOST: redis
      # WP_REDIS_PORT: 6379
    networks:
      - local
    depends_on: 
      - db

networks:
  local:
    driver: bridge
  proxy:
    external: yes
