server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php;

    # Logfiler
    access_log off; # Deaktiver for bedre performance under høj trafik
    error_log /var/log/nginx/error.log crit;

    # Gzip komprimering (Vigtigt for hastighed)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Send PHP forespørgsler til wp-app containeren på port 9000
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # Performance buffers
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    # Cache statiske filer aggressivt
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf)$ {
        expires max;
        log_not_found off;
        access_log off;
    }
}
